FROM mcr.microsoft.com/azureml/base-gpu:intelmpi2018.3-cuda10.0-cudnn7-ubuntu16.04

# Install azureml-sdk to make the code runnable on azureml platform.
# Install azureml-designer-core to enable the handling of built-in data types like DataFrameDirectory, ModelDirectory.
RUN pip install azureml-sdk azureml-designer-core
